---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- directory: Applications/k8s
  children:
  - name: front-back
    type: udm.Application
    children:
    - name: 0.0.81
      type: udm.DeploymentPackage
      children:
      - name: front-ingress
        type: k8s.kubectl.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.81/front-ingress/front-web-front-web-ingress.json"
      - name: front-service
        type: k8s.kubectl.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.81/front-service/front-web-front-web-service.json"
      - name: back-service
        type: k8s.kubectl.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.81/back-service/back-web-back-web-service.json"
      - name: back-deployment
        type: k8s.kubectl.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.81/back-deployment/back-back-back-deployment-1.0.81.json"
      - name: config
        type: k8s.kubectl.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.81/config/config-map.json"
      - name: front-deployment
        type: k8s.kubectl.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.81/front-deployment/front-front-front-deployment-1.0.81.json"
      - name: secret-config
        type: k8s.kubectl.ResourcesFile
        file: !file "./artifacts/Applications/k8s/xl-front-back-app/0.0.81/sensitive-config/config-map.json"
    - name: 0.0.72
      type: udm.DeploymentPackage
      children:
      - name: front-ingress-api
        type: k8s.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.72/front-ingress/front-web-front-web-ingress.json"
      - name: front-service-api
        type: k8s.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.72/front-service/front-web-front-web-service.json"
      - name: back-service-api
        type: k8s.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.72/back-service/back-web-back-web-service.json"
      - name: back-deployment-api
        type: k8s.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.72/back-deployment/back-back-back-deployment-1.0.81.json"
      - name: config-api
        type: k8s.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.72/config/config-map.json"
      - name: front-deployment-api
        type: k8s.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.72/front-deployment/front-front-front-deployment-1.0.81.json"
      - name: secret-config-api
        type: k8s.ResourcesFile
        file: !file "./artifacts/Applications/k8s/xl-front-back-app/0.0.72/sensitive-config/config-map-with-errpr.json"
    - name: 0.0.80
      type: udm.DeploymentPackage
      children:
      - name: front-ingress
        type: k8s.kubectl.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.80/front-ingress/front-web-front-web-ingress.json"
      - name: front-service
        type: k8s.kubectl.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.80/front-service/front-web-front-web-service.json"
      - name: back-service
        type: k8s.kubectl.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.80/back-service/back-web-back-web-service.json"
      - name: back-deployment
        type: k8s.kubectl.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.80/back-deployment/back-back-back-deployment-1.0.81.json"
      - name: config
        type: k8s.kubectl.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.80/config/config-map.json"
      - name: front-deployment
        type: k8s.kubectl.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.80/front-deployment/front-front-front-deployment-1.0.81.json"
      - name: secret-config
        type: k8s.kubectl.ResourcesFile
        file: !file "./artifacts/Applications/k8s/xl-front-back-app/0.0.80/sensitive-config/config-map.json"
    - name: 0.0.83
      type: udm.DeploymentPackage
      children:
      - name: front-ingress
        type: k8s.kubectl.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.83/front-ingress/front-web-front-web-ingress.json"
      - name: front-service
        type: k8s.kubectl.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.83/front-service/front-web-front-web-service.json"
      - name: back-service
        type: k8s.kubectl.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.83/back-service/back-web-back-web-service.json"
      - name: back-deployment
        type: k8s.kubectl.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.83/back-deployment/back-back-back-deployment-1.0.81.json"
      - name: config
        type: k8s.kubectl.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.83/config/config-map.json"
      - name: front-deployment
        type: k8s.kubectl.ResourcesFile
        file: !file "artifacts/Applications/k8s/xl-front-back-app/0.0.83/front-deployment/front-front-front-deployment-1.0.81.json"
      - name: secret-config
        type: k8s.kubectl.ResourcesFile
        file: !file "./artifacts/Applications/k8s/xl-front-back-app/0.0.83/sensitive-config/config-map.json"
 
