language: java
script: "./buildViaTravis.sh"
notifications:
  slack:
    secure: zEpFwp7e5t0dnvd/BX7gFctTB7ZrZ8gFDPMy/fEAP2jaVr2QZ9QMOBaCiHCqeROUQBD6yGG44KmQ9y7YXVIRD2gVBSk8wPVBWyZy7R3ZJZSXzQc/jCWHysOXAc+7Iik5U/8ZBZDN6Nk07g6hrr0Y1b4xhB9j4mQ3g1pL1DzjQycVP1YMUbauslZkPd1vWGBaLVeehge1XeTgoxQrQKFD+MGzaWzUYQbrmXYV5kLslqC4dOotxuUZFPlZOcgg8+l5/RNNCcTnE/AHTn7L0YeZSILdS+0AI3iAzmyyjrGWB5jux+pE4mxpfLSiG4NMYp/nRjsfKSzEHDZq9C0n4yRzgwDYLRBT4jDpPVKLRg/i4pPXKOpUcTUYsh3jwiNZOmg+htkYTMVR7ryVn/b2KMUu8IRz5NtBYwZKLajfcS8SLYscwvxp1OrwGIFScUN0wGqN+My+zqDwtKZ3xNZRU8yzulo0u/HUykm1K91laiobSFA08KjFBcarBr700z8QDdtRloLokxVVZgc8nWD1aKSoLlMbQIhN0IvXgFiN42eloYM/AvSkr3llsFff+7OiZUE2aWEY26RQj6pBC2pij+6oDceKsB1rXaSBueUG7rqJW9DR1Sw5yNtDjbALYtq6LPg47JWxDVfsg/FrySswGtWmLVQ4azqftktd4rU4RSFd7m0=
deploy:
  provider: releases
  api_key:
    secure: fm3PkBz0CDkSePkptQhC1dAtZHxESEuxpAC1tfozROmg5giB+MAtp7TVe9oI01F1GfNVNUacUbT6bI/DYWC94o2R5dlHanYHiF4jSsBKwO+caYFvtvje80c66FwlsVCtaKjFnawFJOY9Ug6dKQncxzJ/0o5cvIJogtm5PdGsKDXfbACNzgvpDpim6Gi9iNYEL7fc7czVTBw+HSBbjHY2/lMiGVc0bcLupI2n/9W2ySnE5C7agoBkEBmEkpZivjqd/lKXgMgi3x2Ugrs1M81kMGb2mUU26T7l2ZRQvalaWvTs/rYVj5I4KnY61xry/CLfavUxCh5Km/fHcYkA44HIhgZSH4HwJcvoLY/3k8FJWKW4yerBY3pP4tdt6XUTyk7o3OSfb8B0MhEe8M1VMkzAmt1XVgnw9N4LpFZOVunIivOrXPrPF4+fpIUNNrmWIWpBqEh1UnDQ6RskU3k5OyRI7LpjIdpijkXnMfvztBZRxqotQ6E7kp3+zbG4+PpCycpU5VuOt3gw6kay0ugWS1vJPaAheA2hPIKq4al8IgJIlMjDvOSxH/uWKasLqh8BOfkZ+g5iShoMR45xGy3icdXDmRWRyz55cmaoHiloR6Ox7fxGziH+CiOWnq+RNebO3FVYJRN8ZaaU1kp9s908ydpswY+hWUfKyj1He7rTMl++dvQ=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  edge: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-k8s-kubectl-plugin
